name: reinf
dependencies:
- alabaster=0.7.6=py34_0
- babel=2.1.1=py34_0
- boost=1.57.0=4
- cmake=3.3.1=0
- cycler=0.9.0=py34_0
- cython=0.23.4=py34_0
- docutils=0.12=py34_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- h5py=2.5.0=np110py34_4
- hdf5=1.8.15.1=2
- icu=54.1=0
- jinja2=2.8=py34_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- mako=1.0.3=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.5.0=np110py34_0
- mkl=11.3.1=0
- nose=1.3.7=py34_0
- numpy=1.10.4=py34_0
- openblas=0.2.14=3
- openssl=1.0.2f=0
- pip=8.0.2=py34_0
- pydot-ng=1.0.0.15=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- python=3.4.4=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.7=py34_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.16.0=np110py34_1
- setuptools=19.6.2=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - keras==0.3.2
  - pyyaml==3.11
  - sphinx-rtd-theme==0.1.7
  - termcolor==1.1.0
  - theano==0.8.0.dev0

